# Generated by Django 2.1.1 on 2018-09-27 04:36

from django.db import migrations
from django.conf import settings
import json


def generate_users(User):
    json_data = open('{}/search/test_users.json'.format(settings.BASE_DIR)).read()
    users = json.loads(json_data)

    user_objs = []
    for user in users:
        user_objs.append(User(
            email=user["email"],
            first_name=user["first_name"],
            last_name=user["last_name"],
            username=user["username"],
            location=user["location"],
            score=user["score"],
            followers=user["followers"],
            repos=user["repos"],
            type=user["type"],
            created=user["created"]
            )
        )
    return user_objs


def forwards_func(apps, schema_editor):
    User = apps.get_model("search", "User")
    db_alias = schema_editor.connection.alias
    User.objects.using(db_alias).bulk_create(generate_users(User))


def reverse_func(apps, schema_editor):
    User = apps.get_model("search", "User")
    db_alias = schema_editor.connection.alias
    User.objects.using(db_alias).all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
